services:
  postgres_test:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-api}
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret}
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DATABASE_USER:-user} -d ${DATABASE_NAME:-api}',
        ]
      interval: 2s
      timeout: 5s
      retries: 10
