export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const PROFILE_REPOSITORY = Symbol('PROFILE_REPOSITORY');
export const VERIFICATION_REPOSITORY = Symbol('VERIFICATION_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const EVENT_BUS = Symbol('EVENT_BUS');
export const AUTHENTICATOR = Symbol('AUTHENTICATOR');
export const SESSION_REPOSITORY = Symbol('SESSION_REPOSITORY');
